export const chapter1 = [
  {
    data:"chapter1_1.jpg",
    type:"image"
  },
  {
    data:"A $9 billion facility will provide rapid and equitable support for COVID‑19 vaccine access."
  },
  {
    data: "The coronavirus disease (COVID‑19) has inflicted an unprecedented toll on the people, society, and economies of Asia and the Pacific, as on the rest of the world. From the loss of life to the lingering social and economic ramifications of measures to contain the virus, the pandemic has affected everyone. In Asia and the Pacific, by December 2020, more than 17 million cases of the disease had been identified, having caused more than 295,000 deaths.",
    type: 'paragraph'
  },
  {
    data:"ADB moved swiftly to deliver flexible support to its developing member countries (DMCs). The bank began refocusing existing projects in late January 2020, and in February provided grants and technical assistance to help governments meet emergency health needs, including for supplies and equipment. ADB also set up a rapid and flexible financing instrument called the COVID‑19 Pandemic Response Option, or CPRO, to help governments protect the poor and vulnerable groups. Additionally, it provided extra support for the private sector, including for trade and supply chains. As the scale of the crisis became clearer, in April ADB expanded its initial allocation for COVID‑19 response and made available up to $20 billion to help governments and the private sector meet emergency needs, provide short-term economic stimulus, and deliver longer-term assistance for sustainable recovery. Further help to secure vaccines followed.",
    type:'paragraph'
  },
  {
    data:"With the pandemic threatening to reverse recent improvements in lives and livelihoods, ADB also continued to focus on projects and programs under the operational priorities of Strategy 2030.",
    type:'paragraph'
  },
  {
    data:"Combining pandemic response with financing under its broader longer-term priorities, ADB’s total commitments from its own resources for lending, grants, guarantees, equity investments, and technical assistance reached $31.6 billion in 2020—32% higher than in 2019. The increase was largely due to the bank’s pandemic support, which accounted for half of its total commitments. This was accompanied by cofinancing of $16.4 billion, including $10.8 billion for COVID‑19 response.",
    type:'paragraph'
  },
  {
    data:"IMPACTS OF THE PANDEMIC IN ASIA AND THE PACIFIC",
    type:'heading'
  },
  {
    data:"The impacts of COVID‑19 have been particularly felt by vulnerable groups: the virus has been particularly severe for the elderly, while children and youth have struggled with school closures. Informal and low-paying jobs have disappeared with women most disadvantaged by those job losses, while travel restrictions have deprived migrant workers of income.",
    type:'paragraph'
  },
  {
    data:"Growth forecasts from the Asian Development Outlook Update 2020 suggest the pandemic has undone 3–4 years of poverty reduction in the developing economies of Asia and the Pacific. COVID‑19 is estimated to have meant an extra 162 million people in the region living under the poverty line of $3.20 per day, and 78 million people in extreme poverty on under $1.90 per day. Recovery from the pandemic will require a renewed focus on inclusive economic growth to address both poverty and growing inequality.",
    type:'paragraph'
  },
  {
    data:"The spread of COVID‑19 during 2020 drove governments across the Asia and Pacific region to impose strict measures to contain the virus. Although these measures varied in their severity, they were all designed to restrict mobility and human interaction, and a plunge in economic activity was the natural consequence. Tourism was particularly hard hit by extensive travel restrictions. To compound the problem, the economies of the region’s major trading partners also contracted sharply, reducing demand for exports.",
    type:'paragraph'
  },
  {
    data:"As a result, ADB estimates that gross domestic product (GDP) shrank across Asia and the Pacific that year—the first contraction in nearly 6 decades. GDP is expected to have shrunk in most of the region’s individual economies while those that expanded will post lower growth rates than in previous years. Small tourism-driven economies like the Cook Islands, Fiji, Palau, and Vanuatu, for example, struggled: visitor arrivals in Fiji fell by over 80% in 2020 to their lowest annual total since 1970, while Palau experienced its first fiscal deficit in 10 years. Meanwhile, the economy of the People’s Republic of China (PRC)—a regional powerhouse—grew by only 2.3%.",
    type:'paragraph'
  },
  {
    data:"The pandemic crippled many micro, small, and medium-sized enterprises (MSMEs) and businesses operating informally. Such operations form the backbone of the regional economy, employing more than 70% of all workers. Asia and the Pacific therefore expects to lose up to 167 million jobs in the immediate term—seven times the number lost during the 2008–2009 global financial crisis.",
    type:'paragraph'
  },
  {
    data:"The region’s 91 million migrant workers were also denied income opportunities for much of 2020. With many of these workers becoming unemployed or receiving significantly reduced pay, remittances to Asia and the Pacific dropped by $54.3 billion over the year compared to 2019.",
    type:'paragraph'
  },
  {
    data:"The pandemic’s economic impact on developing Asia is estimated at between $1.3 trillion and $2.0 trillion lost, equivalent to 5.7%–8.5% of what regional GDP should have been had the pandemic not occurred.",
    type:'paragraph'
  },
  {
    data:"In response, in 2020 ADB DMCs announced policy packages amounting to $3.6 trillion, or 15.2% of regional GDP. DMCs in Central and West Asia announced packages totaling 7.2% of their combined GDP; East Asia 16.4%; the Pacific 7.5%; South Asia 12.7%; and Southeast Asia 13.2%.",
    type:'paragraph'
  },
  {
    data:"ADB’S RAPID AND COORDINATED RESPONSE",
    type:'heading'
  },
  {
    data:"The bank worked closely with development partners and stakeholders to help its DMCs tackle this unprecedented crisis, ensuring the efficient and coordinated deployment of support to deliver maximum impact.",
    type:'paragraph'
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
  {
    data:"",
    type:''
  },
]
