export const chapter3 = [
  {
  data:"Private Sector Operations and the Promotion of Public–Private Partnerships"
  },
  {
    data1:"chapter1_1.jpg",
    type:"chapter3image"
  },
  
  {
    data1:"A doctor administers a vaccine to a child during a vaccination drive in Mandaluyong City, Philippines. ADB has created an interactive mapping tool for the supply chains of vital pandemic-fighting products."
  },
    {
       
      data1:"A doctor administers a vaccine to a child during a vaccination drive in Mandaluyong City, Philippines. ADB has created an interactive mapping tool for the supply chains of vital pandemic-fighting products.",
     type:"paragraph"
    },
    {
      data1:"In 2020, ADB committed private sector investments for 38 projects in critical sectors such as health, agriculture, energy, finance, water, and other urban infrastructure and services. These investments covered 11 developing member countries (DMCs) and included 5 regional projects. The number of private sector projects in 2020 matched that of 2019 despite the pandemic, and the bank remains strongly committed to increasing the share of private sector operations to one third by 2024.",
      type:"paragraph"
    },
     {

      data1:"Following the onset of the COVID‑19 pandemic, ADB swiftly refocused its private sector resources to address the health and economic impacts in its DMCs. With $442 million supporting new COVID‑19 related projects and $2.4 billion in revolving program commitments in trade finance, supply chain finance, and microfinance, 64% of private sector project and program commitments in 2020 directly or indirectly responded to COVID‑19. (Chapter 2 provides examples of country-specific private sector operations.)",
     type:"paragraph"
    }, 
    
      { data1:"In January 2020, the ADB Board of Directors endorsed the operational plan for the bank’s private sector operations. This plan sharpens ADB’s focus on complex, innovative, smaller, and riskier projects in challenging markets and sectors. It also enhances efforts to address climate change and support women. ADB’s private sector operations will support the priorities of the bank’s Strategy 2030, with investments in core areas such as clean energy, environmental infrastructure, agribusiness, quality education and health services, and a vibrant finance sector.",
      type:"paragraph"
    },
    {
      data1:"ADB will expand the sector and geographic reach of its private sector operations, move closer to clients and partners, use more integrated and innovative approaches to tailor this support, and catalyze and mobilize financing.",
    type:"paragraph"
    },
  //   { data"As the COVID‑19 pandemic unleashed a global health crisis, ADB stepped up support for private sector approaches to back quality, efficiency, and financing in health infrastructure.",
  //   data"As early as February 2020, ADB provided working capital support of $18.5 million to Wuhan based pharmaceutical firm Jointown to ensure continued supply of essential medical supplies and personal protective equipment. An additional loan of $36.7 million helped Jointown expand its distribution capacity to reach more hospitals and retail pharmacy outlets in underserved areas. The expanded distribution facilities include cold chain warehouses for temperature-sensitive pharmaceutical products such as vaccines. ADB also signed an $8 million loan with Imexpharm Corporation to help the company sustain its production of generic medicines in Viet Nam despite global supply disruptions.",
  //   data"Encompassing agricultural manufacturing and services as well as production, agribusiness is critical to economic and social development in Asia and the Pacific. It contributes as much as a third of gross domestic product in most DMCs. The pandemic has, however, caused significant disruptions in the agriculture value chain.",
  //   data"Smallholder farmers across the region are acutely vulnerable to worsening poverty as their incomes were below average even before the pandemic. Local market closures and declining demand from small traders have reduced their earnings and increased food wastage.",
  //   data:"As just one example of broader support for agribusiness, ADB provided $93.8 million in financing to Olam International Limited. This helped the company buy more coffee, cacao, and other high-value crops from at least 100,000 smallholder farmers in Viet Nam, Indonesia, and Papua New Guinea. Headquartered in Singapore, Olam buys directly from growers and agents at the farm gate. The ADB investment taps into the company’s capacity to provide a coordinated regional solution for smallholder farmers impacted by domestic market limitations. ",
  //   data:"ADB is also working to extend private sector investment into more economies of Asia and the Pacific where development needs go unfinanced and unmet because of real or perceived investment risks.",
  //   data:"The bank signed loans for the first private sector gas-fired power plant in Afghanistan to be funded by development finance institutions. ADB committed a $20 million financing package to Afghan Power Plant Company Limited. The project represents a significant private sector engagement by ADB to support essential infrastructure in a fragile and conflict-affected economy. The loans will help build and operate a 58.56-megawatt (MW) gas-fired power plant, generating 404 gigawatt-hours of power annually and supporting Afghanistan’s efforts to achieve long-term energy security.",
  //   data:"ADB’s first grant-based concessional facility for nonsovereign operations, the ADB Private Sector Window is an innovative pilot program to promote private sector growth in low-income countries. The fund was established to help reduce shared financing constraints that hinder private sector operations, especially in fragile and conflict-affected situations and small island developing states. It has three tailored investment solutions: blended finance, local currency risk mitigation, and loan guarantees. The program will encourage and mobilize private sector investment through co-investments and partnerships with other development financial institutions, commercial lenders, and institutional investors for highly developmental projects, including in agribusiness, education, health, financial institutions, and nontraditional infrastructure.",
  //   data:"The opening of ADB’s new office in Singapore in March marked a pivotal stage in the expansion of the bank’s private sector operations. As a financial hub, Singapore’s sophisticated private and public sector ecosystems will help mobilize investments and bring the latest technologies and management skills to development projects across the Asia and Pacific region. The new office allows ADB to work more closely with stakeholders, including key investors and sponsors, leveraging the bank’s strengths in infrastructure and innovation to support DMCs.",
  //  data"In 2020, ADB invested in Clifford Capital Holdings (CCH), a specialist global financing and distribution platform for infrastructure and other real assets, headquartered in Singapore. The transaction comprised $50 million from ADB and $45 million from the Japan International Cooperation Agency-funded Leading Asia’s Private Sector Infrastructure Fund (LEAP). To maintain growth, tackle poverty, and address climate change, developing Asia and the Pacific needs $1.7 trillion annually in infrastructure financing through to 2030, and CCH’s focus on financial innovation through securitization can help meet these financing needs.",
  //  data"PIONEERING INNOVATION AND MOBILIZING FINANCE Of the $2 billion in long-term cofinancing ADB mobilized in 2020, about 87% came from commercial cofinancing partners, with the rest from official sources. Every $1 of ADB’s committed nonsovereign financing was matched by $2.12 in long-term cofinancing—up from $1.50 during 2019 and on track to achieving the 2030 target of mobilizing $2.50 in long-term cofinancing for every $1 of ADB financing.",
  //   data:"ADB provided financing, through Viet Nam’s first certified green loan, for Phu Yen TTP Joint Stock Company to develop and operate a 257 MW solar power plant. The financing comprises a $27.9 million loan funded by ADB, a $148.8 million B loan funded by commercial banks, and a $9.3 million loan from LEAP. The syndicated loan is the first green B loan in Asia and the Pacific to be certified by the Climate Bonds Initiative, and one of the largest such loans yet mobilized in the country. The project is the single largest operating solar power plant in Viet Nam and one of the largest in Southeast Asia.",
  //   data:"In Bangladesh, ADB provided $100 million to Reliance Bangladesh LNG and Power Limited to build and operate a 718 MW combined-cycle gas-fired power plant. ADB also administered $100 million from LEAP in cofinancing. ADB has been instrumental in mobilizing crucial commercial financing, incorporating best practices in environmental and social standards, and establishing precedents for future financing of similar large-scale projects in Bangladesh by boosting investor and lender confidence.",
  //   data:XPANDING ACCESS TO VENTURE CAPITAL Launched in 2020, ADB Ventures is the venture arm of ADB and invests in early-stage technology companies that address urgent development problems in emerging Asia and the Pacific. ADB Ventures aspires to crowd in more than $1 billion of risk capital toward achievement of the Sustainable Development Goals by 2030.",
  //    data:"ADB recognizes that spurring innovators to expand into frontier markets requires a multi-pronged approach that addresses financing gaps across multiple stages of a young company’s business life cycle. Having raised its first fund in 2020 with $60 million in commitments, ADB Ventures Investment Fund 1 focuses on climate and gender impact in South and Southeast Asia. The fund co-invests with the private sector in pre-Series A and Series A stage companies. ADB Ventures’ Seed program provides up to $200,000 catalytic funding, typically at seed stage, giving ADB the option to make future equity investments in these companies. These products enable early-stage companies to validate and commercialize their products and services in emerging markets.",
  //    data:" The ADB Ventures Labs program leverages ADB’s operational networks, relationships, and strategic partners to match regional demand for technology solutions to best-in-class technology companies. The Labs program helps portfolio companies scale and identify investment opportunities.",
  //   data:" Inaugural investors in ADB Ventures Investment Fund 1 include Finland’s Ministry for Foreign Affairs, the Clean Technology Fund, the Nordic Development Fund, the Korea Venture Investment Corporation, and the Republic of Korea e-Asia and Knowledge Partnership Fund. The ADB Ventures Seed and Labs programs are cofinanced by the Clean Technology Fund, the Asia-Pacific Climate Finance Fund, and the Nordic Development Fund. The Nordic Development Fund, the Clean Technology Fund, and the Government of Australia cofinanced the preparation of ADB Ventures.",
  //   data:" The technical assistance program’s innovative ADB Ventures Labs initiative helped more than 50 early-stage companies explore opportunities to scale up by matching these enterprises with public sector client networks as well as corporate partners in commercial real estate, hospitality, agrifood, and water treatment.",
  //   data:"ADB’s vision is for ADB Ventures to become the largest venture capital platform for technology in Asia and the Pacific.",
    
    
    
]